# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Castle
email: blog@crc.io
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://crc.io" # the base hostname & protocol for your site
twitter_username: crc
github_username:  crcastle

# Build settings
encoding: utf-8
markdown: kramdown
destination: ../blog
permalink: /:year/:month/:title/
